### ISSUE TITLE
Hosted window requires customer to ender adress etc. again

### ISSUE THREAD

**Issue by navbeacon** [DIBS-Payment-Services/opencart30_dibseasy#8]
By the screenshot on the main github page it looks like the hosted window only handles the payment, while using the already entered customer data during the earlier checkout steps. When we try this however, the customer needs to again enter email, zipcode, phone and address. Can this be avoided?

There are no errors logged. What can I do to make this easier to troubleshoot?
Thanks!

**Comment by maxwhite** [comment]
Could you please write to me to:
mbelo@nets.eu
